### ISSUE TITLE
importing home modules into a system configuration

### ISSUE THREAD

**Issue by michaelBelsanti** [snowfallorg/lib#50]
I am converting my flake to use snowfall. It has 1 home-manager configuration and 2 nixos configurations. Both NixOS configurations also import and use home-manager. I have created some modules at home/modules which are not automatically imported by home-manager within the system configurations. Is it possible to have these automatically imported, or is there a manual way to do so?

**Comment by jakehamilton** [comment]
Hi there, this bug should be fixed on the dev branch as of this PR: https://github.com/snowfallorg/lib/pull/48

Can you try the latest version from there?

**Comment by michaelBelsanti** [comment]
Unfortunately the issue still seems to be happening. Home-manager within my system configurations are not importing any of the modules from `modules/home`. I have some options defined in their, which I cannot enable in my system's default.nix.

**Comment by michaelBelsanti** [comment]
I also have a file at modules/nixos/generic/default.nix that does not seem to be getting imported by my system configuration.

**Comment by jakehamilton** [comment]
@michaelBelsanti can you make sure that you've run `git add`?

If that doesn't solve it then it would be helpful if you could push your whole flake up to a repo so I can take a look.

**Comment by michaelBelsanti** [comment]
Yeah, they're all added. I might be missing something simple, I was converting a fairly large flake to use Snowfall. Here's my flake: https://github.com/michaelBelsanti/nixconfig/tree/snowfall

**Comment by jakehamilton** [comment]
@michaelBelsanti which file(s) in the repo you shared aren't working? I don't see the generic directory you mentioned.

**Comment by michaelBelsanti** [comment]
My bad, was doing a lot of rebasing and screwed up some commits. They're both there now under `modules/home/default` and `modules/nixos/default`.

**Comment by msfjarvis** [comment]
I've also run into this problem even though I'm on the dev branch. My changes are [here](https://github.com/msfjarvis/dotfiles/compare/snowfall), and I've confirmed via `nvd diff` that I'm definitely seeing all home-manager modules getting ignored.


<details>
<summary>nvd diff output</summary>

```
<<< /nix/var/nix/profiles/system-120-link
>>> result
Version changes:
[C.]  #01  brotli                 1.1.0-lib x2 -> 1.1.0, 1.1.0-dev, 1.1.0-lib x2
[C*]  #02  bzip2                  1.0.8 x2, 1.0.8-bin x2, 1.0.8-man -> 1.0.8 x2, 1.0.8-bin x2, 1.0.8-dev, 1.0.8-man
[C.]  #03  cairo                  1.18.0 x2 -> 1.18.0 x2, 1.18.0-dev
[C*]  #04  fontconfig             2.15.0 x2, 2.15.0-bin, 2.15.0-lib x2 -> 2.15.0 x2, 2.15.0-bin, 2.15.0-dev, 2.15.0-lib x2
[C.]  #05  fonts.conf             <none> x2 -> <none>
[C.]  #06  freetype               2.13.2 x2 -> 2.13.2 x2, 2.13.2-dev
[C.]  #07  libX11                 1.8.7 x2 -> 1.8.7 x2, 1.8.7-dev
[C.]  #08  libXau                 1.0.11 x2 -> 1.0.11 x2, 1.0.11-dev
[C.]  #09  libXext                1.3.5 x2 -> 1.3.5 x2, 1.3.5-dev
[C.]  #10  libXrender             0.9.11 x2 -> 0.9.11 x2, 0.9.11-dev
[C.]  #11  libpng-apng            1.6.40 x2 -> 1.6.40 x2, 1.6.40-dev
[C.]  #12  libxcb                 1.16 x2 -> 1.16 x2, 1.16-dev
[C.]  #13  lua                    5.2.4, 5.2.4-env, 5.4.6 -> 5.4.6
[D.]  #14  nixos-system-ryzenbox  24.05.20240218.34d1661 -> 24.05.20240218.e015f24
[C.]  #15  python3                3.11.7 x3, 3.11.7-env x6 -> 3.11.7 x3, 3.11.7-env x5
[C.]  #16  python3.11-pygobject   3.46.0 -> 3.46.0, 3.46.0-dev
[C.]  #17  qrencode               4.1.1 x2, 4.1.1-bin -> 4.1.1 x2
[C.]  #18  source                 <none> x19 -> <none> x21
[C.]  #19  vte                    0.74.2 x2 -> 0.74.2 x3
Added packages:
[A.]  #1  python3.11-cython      0.29.36
[A.]  #2  python3.11-manimpango  0.5.0
[A.]  #3  smile                  2.9.0
[A.]  #4  uv                     0.1.3
[A.]  #5  xorgproto              2023.2
Removed packages:
[R.]  #01  browserpass                                         3.1.0
[R.]  #02  chafa                                               1.14.0
[R.]  #03  code-url-handler.desktop                            <none>
[R.]  #04  code.desktop                                        <none>
[R.]  #05  dmenu                                               5.2
[R.]  #06  extensions-json                                     <none>
[R.]  #07  gcc-wrapper                                         13.2.0
[R.]  #08  getopt                                              1.1.6
[R.]  #09  git-sync-password-store.service                     <none>
[R.]  #10  git-sync-unstable                                   2022-03-20
[R.]  #11  hm_mpvmpv.conf                                      <none>
[R.]  #12  inotify-tools                                       4.23.9.0
[R.]  #13  libXpresent                                         1.0.1
[R.]  #14  libbacktrace-unstable                               2023-11-30
[R.]  #15  libdovi                                             3.1.2
[R.]  #16  libplacebo                                          6.338.2
[R.]  #17  lua5.2-luasocket                                    3.1.0-1
[R.]  #18  mpv                                                 0.37.0 x2, 0.37.0-dev, 0.37.0-doc, 0.37.0-man
[R.]  #19  mpv-inhibit-gnome                                   0.1.3
[R.]  #20  mpv-thumbfast-unstable                              2023-12-08
[R.]  #21  mpv-with-scripts                                    0.37.0
[R.]  #22  mujs                                                1.3.4
[R.]  #23  nixd                                                1.2.3
[R.]  #24  oath-toolkit                                        2.6.10
[R.]  #25  pass-audit                                          1.2, 1.2-man
[R.]  #26  pass-env                                            <none>
[R.]  #27  pass-genphrase                                      0.3
[R.]  #28  pass-otp                                            1.2.0
[R.]  #29  pass-update                                         2.1
[R.]  #30  password-store                                      1.7.4
[R.]  #31  python3.11-setuptools                               69.0.3
[R.]  #32  python3.11-zxcvbn                                   4.4.28
[R.]  #33  rubberband                                          3.3.0
[R.]  #34  rust-analyzer-nightly-b9b0d29                       <none>
[R.]  #35  shaderc                                             2023.8-lib
[R.]  #36  starship-config                                     <none>
[R.]  #37  topgrade                                            14.0.1
[R.]  #38  topgrade-config                                     <none>
[R.]  #39  tree                                                2.1.1
[R.]  #40  uchardet                                            0.0.8
[R.]  #41  uosc                                                5.1.1
[R.]  #42  uosc-bin                                            5.1.1
[R.]  #43  vamp-plugin-sdk                                     2.10
[R.]  #44  vscode                                              1.86.2
[R.]  #45  vscode-extension-arrterian-nix-env-selector         1.0.11
[R.]  #46  vscode-extension-eamodio-gitlens                    2024.2.1704
[R.]  #47  vscode-extension-github-vscode-github-actions       0.26.2
[R.]  #48  vscode-extension-jnoortheen-nix-ide                 0.2.2
[R.]  #49  vscode-extension-k--kato-intellij-idea-keybindings  1.5.13
[R.]  #50  vscode-extension-ms-vscode-remote-remote-ssh        0.109.2024021615
[R.]  #51  vscode-extension-ms-vscode-remote-remote-ssh-edit   0.86.0
[R.]  #52  vscode-extension-mtdmali-daybreak-theme             1.2.0
[R.]  #53  vscode-extension-oderwat-indent-rainbow             8.3.1
[R.]  #54  vscode-extension-rust-analyzer-b9b0d29              <none>
[R.]  #55  vscode-extension-tamasfe-even-better-toml           0.19.2
[R.]  #56  vscode-extensions                                   <none>
[R.]  #57  vscode-user-settings                                <none>
[R.]  #58  zellij                                              0.39.2
```

</details>

**Comment by jakehamilton** [comment]
@michaelBelsanti after taking a look, it seems like your directory structure is a bit off. Your Home must be defined as `homes/<arch>-<system>/<user>@<host>/default.nix`. Though I only see a `homes/x86_64-linux/default.nix` which isn't being picked up. You can find a reference usage of this pattern in my configuration: https://github.com/jakehamilton/config/tree/main/homes

**Comment by jakehamilton** [comment]
@msfjarvis I took a look and it seems your home modules are being evaluated and used just fine. `nvd` may not be displaying packages that are made available via home-manager.

**Comment by msfjarvis** [comment]
> @msfjarvis I took a look and it seems your home modules are being evaluated and used just fine. `nvd` may not be displaying packages that are made available via home-manager.

Sadly that's not the case, when I switch the `ryzenbox` machine to the `snowfall` branch none of the home-manager features are active. `/etc/profiles/per-user/msfjarvis/etc/profile.d/hm-session-vars.sh` stops existing, and the starship module declared [here](https://github.com/msfjarvis/dotfiles/blob/snowfall/modules/home/starship/default.nix) no longer generates its configuration file.

**Comment by jakehamilton** [comment]
@msfjarvis can you try updating to the latest release on `dev` and rebuilding?

**Comment by msfjarvis** [comment]
> @msfjarvis can you try updating to the latest release on `dev` and rebuilding?

Updated to [d2210cdc1404b59f380ac6f8e3871676dc5c7a07](https://github.com/snowfallorg/lib/commit/d2210cdc1404b59f380ac6f8e3871676dc5c7a07) and rebuilt, still getting the same result :(

**Comment by msfjarvis** [comment]
I believe the latest push to dev resolved the problem for me, but I don't have access to all my machines for the next couple days so can only confirm it for one of my NixOS configs.

**Comment by msfjarvis** [comment]
Was able to get some time on my MacBook and discovered a few leftover issues in my migration, everything works perfectly fine on that as well with nix-darwin. Here is the final commit in case it's of any interest: https://github.com/msfjarvis/dotfiles/commit/2016506a560cbee3d77ffcd99efad0bf5da832b9

**Comment by jakehamilton** [comment]
Awesome, thanks for checking @msfjarvis!

**Comment by michaelBelsanti** [comment]
> @michaelBelsanti after taking a look, it seems like your directory structure is a bit off. Your Home must be defined as `homes/<arch>-<system>/<user>@<host>/default.nix`. Though I only see a `homes/x86_64-linux/default.nix` which isn't being picked up. You can find a reference usage of this pattern in my configuration: https://github.com/jakehamilton/config/tree/main/homes

Sorry I think I was a bit unclear in my issue. I'm not currently using any homes, the files in the homes directory are just placeholders from my previous configuration, until I'm done converting to snowfall. Currently, I am only using the two systems, nix-laptop and nix-desktop. I'm trying to use the home-manager modules I've created in modules/home, within my system configurations that are importing home-manager.

**Comment by jakehamilton** [comment]
@michaelBelsanti home modules are only loaded if you have a home defined for the system. You'll need to add a home (in "homes/user@system/default.nix") for it to be accessible.

**Comment by michaelBelsanti** [comment]
I see, thanks. Will it be necessary to use the home-manager CLI with this, or can I import a home into a system configuration? I prefer to use home-manager as a NixOS module.

**Comment by jakehamilton** [comment]
@michaelBelsanti homes are automatically added to NixOS systems if the host name matches 👍

**Comment by michaelBelsanti** [comment]
Awesome! Thanks for your help!

In that case, I expect the issue to be solved when I add the home. I'll test it later today.

**Comment by LovingMelody** [comment]
May help to add an example to [snowfallorg/templates](https://github.com/snowfallorg/templates) for this for future users
