### ISSUE TITLE
homeModules unable to reference nixosModule enable software

### ISSUE THREAD

**Issue by queer-bird** [snowfallorg/lib#60]
I'm not sure if I'm simply using it improperly but maybe you can set me on the proper path. I have modules in a git repository, basing it on the snowflakeos-modules. The only change I have made so far is attempting to integrate stylix in the modules. Simple enough, I add a home folder to the module folder and added stylix to the inputs, and added snowflakeos.homeModules.stylix to my personal flake.

First thing I found confusing, when I first tried rebuilding NixOS it told me there was no stylix option. So I imported the stylix input inside the module and that fixed that problem. But isn't snowfall lib supposed to automatically inherit inputs into all of your modules? Does this not apply to home modules?

Onto the main problem I want to ask about. After I did that it tells me  `error: The option `dconf' does not exist. Definition values:` which is a common problem with stylix/home-manager. The answer is usually to enable dconf in the nixos config. So I enable dconf within the repository containing the module, and that doesn't help.  I enable it in my nixos configuration on my system and that doesn't help. Shouldn't snowfall lib allow the module to inherit the config?

This problem does not occur if I simply hold the module locally on my config, but I want to use homeModules in a git repository for many ideas I have so if I can figure it out that would be great.

Thank you for your time, your project is very promising. Sorry if my request is a bit rough, I am not so used to the whole github thing

**Comment by pinkcreeper100** [comment]
@queer-bird iirc stylix is broken

**Comment by jakehamilton** [comment]
Hey there! I believe this may be one of the things that is fixed in the next version of Snowfall Lib. Can you try switching to using the dev branch `github:snowfallorg/lib/dev` instead?

Information on using the new, currently unreleased, version is available here: https://snowfall.org/guides/lib/migration/v3/

If that doesn't solve the problem, could you share your whole flake and config in a github repository?

**Comment by queer-bird** [comment]
Oh, I read that migration section but somehow missed the detail that it wasn't merged yet. Darn you, Dyslexia!

Anyway, migrated to the dev branch and I am still getting this issue, so here are the relevant repositories.


The local config
https://codeberg.org/Prax-OS/prax-template/src/branch/dev

The remote modules
https://codeberg.org/Prax-OS/prax-modules/src/branch/main/modules

Sorry the files are all a bit messy, just got done shoving multiple flakes into each other and I just want to solve this problem before making a bunch of optimizations.

Thank you for your help

**Comment by jakehamilton** [comment]
I'm not too sure what problem you're running into here. I don't think it is Snowfall Lib causing the problem. Perhaps it would be useful to reference the systems documentation which shows how to add modules to hosts?

https://snowfall.org/guides/lib/systems/

Snowfall Lib only integrates with home-manager and nixos-generators, it doesn't automatically import other flake inputs inside of your modules. That has to be done by the author.
